## Importing files & Scraping pdf

In [1]:
import pandas as pd
import camelot

pdf_path = "C:/Users/user/OneDrive - Hetauda School of Management and Social Sciences/Desktop/Data Analysis/Projects/Project V/Raw Datas/SUN2000-200KTL-H2-Datasheet-20230822.pdf"
tables = camelot.read_pdf(pdf_path, flavor = 'stream', pages = '2', edge_tol = 100);

data = tables[0].df
data

,0,1
0,,Efficiency
1,Max. Efficiency,≥99.00%
2,European Efficiency,≥98.80%
3,,Input
4,Max. Input Voltage,"1,500 V"
5,Max. Current per MPPT,30 A
6,Max. Short Circuit Current per MPPT,50 A
7,Start Voltage,550 V
8,MPPT Operating Voltage Range,"500 V ~ 1,500 V"
9,Nominal Input Voltage,"1,080 V"
10,Number of Inputs,18
11,Number of MPP Trackers,9
12,,Output
13,AC Output Power,"200,000 W*"
14,Max. AC Apparent Power,"215,000 VA"
15,Max. AC Active Power (cosφ=1),"215,000 W"
16,Nominal Output Voltage,"800 V, 3W + PE"
17,Rated AC Grid Frequency,50 Hz / 60 Hz
18,Nominal Output Current,144.4 A**
19,Max. Output Current,155.2 A
20,Adjustable Power Factor Range,0.8 LG ... 0.8 LD
21,Max. Total Harmonic Distortion,＜1%
22,,Protection
23,Input-side Disconnection Device,Yes
24,Anti-islanding Protection,Yes
25,AC Overcurrent Protection,Yes
26,DC Reverse-polarity Protection,Yes
27,PV-array String Fault Monitoring,Yes
28,DC Surge Arrester,Type II
29,AC Surge Arrester,Type II
30,DC Insulation Resistance Detection,Yes
31,Residual Current Monitoring Unit,Yes
32,,Communication
33,Display,"LED Indicators, WLAN + APP"
34,USB,Yes
35,MBUS,Yes
36,RS485,Yes
37,,General
38,Dimensions (W x H x D),"1,035 x 700 x 365 mm (40.7 x 27.6 x 14.4 inch)"
39,Weight (with mounting plate),≤86 kg (189.6 lb.)
40,Operating Temperature Range,-25°C ~ 60°C (-13°F ~ 140°F)
41,Cooling Method,Smart Air Cooling
42,Max. Operating Altitude without Derating,"4,000 m (13,123 ft.)"
43,Relative Humidity,0 ~ 100%
44,DC Connector,Staubli MC4 EVO2
45,AC Connector,Waterproof Connector + OT/DT Terminal
46,Protection Degree,IP66
47,Topology,Transformerless
48,*When environmental temperature is 50℃，AC Outp...,
49,**When environmental temperature is 50℃，Nomina...,

## Data Cleaning

In [12]:
target_params = [
    "Max. Efficiency", "European Efficiency", "Max. Input Voltage", 
    "MPPT Operating Voltage Range", "Max. Current per MPPT", 
    "AC Output Power", "Max. AC Apparent Power", "Nominal Output Voltage", 
    "Max. Output Current", "Number of MPP Trackers"
]

df_clean = data[data[0].isin(target_params)].copy();


df_clean.loc[:, 1] = df_clean[1].str.replace(',', ''); 


df_clean.loc[:, 1] = df_clean[1].str.extract(r'(\d[\d\s\.\~]*)')[0].str.strip()
# \d: Start with exactly one digit (0-9). This ensures we don't grab symbols like ≥ or <.
# [ ... ]*: This is a "character class" that says: "After that first digit, keep grabbing anything inside these brackets until you hit something else."
# \d: More digits.
# \s: Spaces (needed for ranges like 500 ~ 1500).
# \.: Decimal points (for values like 99.8).
# \~: The tilde symbol (to keep ranges intact).

df_clean.loc[:, 1] = df_clean[1].str.replace('~', '-')

category_map = {
    "Max. Efficiency": "Performance", "European Efficiency": "Performance",
    "Max. Input Voltage": "Input", "MPPT Operating Voltage Range": "Input",
    "Max. Current per MPPT": "Input", "AC Output Power": "Output",
    "Max. AC Apparent Power": "Output", "Nominal Output Voltage": "Output",
    "Max. Output Current": "Output", "Number of MPP Trackers": "Design"
}
df_clean.loc[:, 'Category'] = df_clean[0].map(category_map)


df_clean.columns = ['Parameter', 'Value', 'Category']

eff_mask = df_clean['Parameter'].str.contains('Efficiency')
df_clean.loc[eff_mask, 'Value'] = df_clean.loc[eff_mask, 'Value'] + '%'

df_clean

                       Parameter   Value     Category
1                Max. Efficiency  99.00%  Performance
2            European Efficiency  98.80%  Performance
4             Max. Input Voltage    1500        Input
5          Max. Current per MPPT      30        Input
8   MPPT Operating Voltage Range     500        Input
11        Number of MPP Trackers       9       Design
13               AC Output Power  200000       Output
14        Max. AC Apparent Power  215000       Output
16        Nominal Output Voltage     800       Output
19           Max. Output Current   155.2       Output

## Exporting